networks:
  flink-network-1:
  flink-network-2:

services:
  jobmanager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jobmanager
    networks:
      - flink-network-1
      - flink-network-2
    ports:
      - '8081:8081'
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
      
  taskmanager:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - jobmanager
    deploy:
      replicas: 2
    networks:
      - flink-network-1
      - flink-network-2
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
