# It is not necessary to use this Dockerfile as you can also create a .jar file
# using Maven and copy the .jar file to the /docker-app/jobs directory. Make
# sure to change the port "localhost:9092" to "kafka:29092".
FROM flink:1.17.1-scala_2.12

# RUN wget -P /opt/flink/lib https://repo1.maven.org/maven2/org/apache/flink/flink-streaming-java/1.17.1/flink-streaming-java-1.17.1.jar
# RUN wget -P /opt/flink/lib https://repo1.maven.org/maven2/org/apache/flink/flink-clients/1.17.1/flink-clients-1.17.1.jar

# RUN wget -P /opt/flink/lib https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-kafka/1.17.1/flink-connector-kafka-1.17.1.jar
# RUN wget -P /opt/flink/lib https://repo1.maven.org/maven2/org/apache/flink/flink-connector-datagen/1.17.1/flink-connector-datagen-1.17.1.jar
# RUN wget -P /opt/flink/lib https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.4.0/kafka-clients-3.4.0.jar
# RUN wget -P /opt/flink/lib https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.15.2/jackson-core-2.15.2.jar
# RUN wget -P /opt/flink/lib https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.15.2/jackson-databind-2.15.2.jar
